# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/leaderboard
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.game_score=game_score
spring.kafka.consumer.group-id=ws_consumer
spring.kafka.consumer.auto-offset-reset=earliest

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# ===============================
# Redis Configuration
# ===============================
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=60000


# ===============================
# WebSocket Configuration
# ===============================
spring.websocket.message-broker.enabled=true
spring.websocket.message-broker.simple-broker.enabled=true
spring.websocket.stomp.endpoint=/leaderboard


# ===============================
# Server Port Configuration (Optional)
# ===============================
server.port=8080


# ===============================
# Logging Configuration
# ===============================
logging.level.org.springframework.kafka=DEBUG
logging.level.org.springframework.data.redis=DEBUG
